{
    "name": "ISO",
    "author": "Clent Japhet Poledo",
    "version": "1.0",
    "summary": "Tools for managing ISO-related documents",
    "application": True,
    "data": [
        "security/security_groups.xml",
        "security/access_control_list.xml",
        "security/record_rules.xml",
        "reports/rsmi.xml",
        "reports/ris.xml",
        "views/menu.xml",
        "views/stock.xml",
        "views/issuances.xml",
        "views/rc.xml",
        "views/category.xml",
        "views/measure_units.xml",
        "views/summary_report.xml",
        "views/replenishment_logs.xml",
        "views/rsmi.xml",
        "views/procurement.xml",
        "views/procurement_wizard.xml",
        "views/ris.xml",
        "views/fund_cluster.xml",
        "views/stock_fund_balance.xml",
        "views/ppmp.xml",
        "views/reset_wizard.xml",
    ],
    "icon": "upmin_stock/static/description/logo.jpeg",
    "license": "Other proprietary",
}
