{
    "name": "ISO",
    "author": "Clent Japhet Poledo",
    "version": "1.7",
    "summary": "Tools for managing ISO-related documents",
    "application": True,
    "depends": [
        "hr",
        "upmin_hr_ext",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/iso_clause_data.xml",
        "views/internal_auditor.xml",
        "views/document_controller.xml",
        "views/unit_head.xml",
        "views/swot.xml",
        "views/tows.xml",
        "views/swot_tows_export_wizard.xml",
        "views/iso_clause.xml",
        "views/institutional_finding.xml",
        "views/institutional_finding_wizard.xml",
        "views/audit_period.xml",
        "report/ccar_report_template.xml",
        "report/audit_findings_report.xml",
        "views/audit_info.xml",
        "views/audit_finding_merge_wizard.xml",
        "views/ccar.xml",
        "views/swot_line_close_wizard.xml",
        "views/ror.xml",
        "views/ror_export_wizard.xml",
        "views/ror_import_wizard.xml",
        "views/significant_risks_export_wizard.xml",
        "views/iso_dashboard.xml",
        "views/iso_access_group.xml",
        "views/iso_role_membership.xml",
        "views/menu.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "upmin_iso/static/src/js/ror_tree_extend.js",
            "upmin_iso/static/src/js/delete_confirm.js",
            "upmin_iso/static/src/js/html_tooltip_strip.js",
            "upmin_iso/static/src/xml/ror_list_button.xml",
            "upmin_iso/static/src/scss/ror_button.scss",
            "upmin_iso/static/src/scss/audit_finding_list.scss",
        ],
    },
    "icon": "upmin_iso/static/description/logo.jpeg",
    "license": "Other proprietary",
}
