{
    "name": "UPMin Inventory",
    "author": "Clent Japhet Poledo",
    "version": "1.0",
    "application": True,
    "depends": [
        "report_xlsx",
    ],
    "data": [
        "security/security_groups.xml",
        "security/access_control_list.xml",
        "views/menu.xml",
        "views/stock.xml",
        "views/issuances.xml",
        "views/rc.xml",
        "views/category.xml",
        "views/measure_units.xml",
        "views/summary_report.xml",
        "views/replenishment_logs.xml",
        "views/rsmi.xml",
        "views/procurement.xml",
        "views/procurement_wizard.xml",
        # "views/ris.xml",
        "reports/rsmi.xml",
    ],
}
